---
title: LiteSheet
timezone: UTC
collections:
  companies:
    title: Companies
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
markdown: kramdown
plugins:
- jekyll-feed
copyright_name: LiteSheet
highlighter: rouge
permalink: pretty
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
